plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Sławek\\Documents\\.MD\\PARA\\SER\\10_PROJEKTY\\SIDE_WWW\\cleen_roofs\\src\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]